name: Deploy MkDocs to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-mkdocs-${{ hashFiles('mkdocs.yml') }}
          path: ~/.cache/pip
          restore-keys: |
            ${{ runner.os }}-mkdocs-

      - name: Install dependencies
        run: |
          pip install mkdocs-material mkdocs-static-i18n

      - name: Deploy MkDocs
        run: mkdocs gh-deploy --force
